---
language: python
python:
  - "2.7"
  - "3.6"

services:
  - docker
install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Install molecule
  - pip install testinfra molecule docker

  # Check molecule version 
  - molecule --version
before_script:
  - docker pull centos/systemd

script:
  - molecule test
