---
# Создаем папки на удаленной машине
- name: NOMAD | Creating conf directory
  file:
    path: "{{ nomad_conf_dir }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0755"
  tags:
    - directory
    - config_file
    - configs

# Создаем папки на удаленной машине
- name: NOMAD | Creating logs directory
  file:
    path: "{{ nomad_logs_dir }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0755"
  tags:
    - directory
    - logs_directory

- name: NOMAD | Creating data/plugin directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0700"
  loop:
    - "{{ nomad_data_dir }}"
    - "{{ nomad_plugin_dir }}"
  tags:
    - directory

- name: NOMAD | Creating server data directory
  file:
    path: "{{ nomad_server_data_dir }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0700"
  when: nomad_server_enabled | bool
  tags:
    - directory

- name: NOMAD | Creating client directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0700"
  loop:
    - "{{ nomad_client_alloc_dir }}"
    - "{{ nomad_client_state_dir }}"
  when: nomad_client_enabled | bool
  tags:
    - directory

# Создаем конфигурационный файл сервиса
- name: NOMAD | Creating base configuration file
  template:
    src: "nomad.hcl.j2"
    dest: "{{ nomad_conf_dir }}/nomad.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0644"
  register: nomad_main_config_file
  tags:
    - config_file
    - configs

# Создаем конфигурационный файл сервиса
- name: NOMAD | Creating server configuration file
  template:
    src: "server.hcl.j2"
    dest: "{{ nomad_conf_dir }}/server.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0644"
  register: nomad_server_config_file
  when: nomad_server_enabled | bool
  tags:
    - config_file
    - configs

# Создаем конфигурационный файл сервиса
- name: NOMAD | Creating client configuration file
  template:
    src: "client.hcl.j2"
    dest: "{{ nomad_conf_dir }}/client.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0644"
  register: nomad_client_config_file
  when: nomad_client_enabled | bool
  tags:
    - config_file
    - configs

# Создаем конфигурационный файл systemd
- name: NOMAD | Creating systemd config file
  template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/nomad.service"
    owner: root
    group: root
    mode: "0644"
  register: nomad_systemd_file
  tags:
    - systemd_config_file
    - configs

# Перезагружаем сервис
- name: NOMAD | Restart nomad
  systemd:
    name: nomad
    state: restarted
    daemon_reload: true
  when:
    - "'nomad.service' in services"
    - nomad_main_config_file.changed or
      nomad_server_config_file.changed or
      nomad_client_config_file.changed or
      nomad_systemd_file.changed

# Убеждаемся что сервис запущен и добавлен в автозапуск
- name: NOMAD | Ensure nomad is started and enabled a boot
  systemd:
    name: nomad
    state: "{{ nomad_state }}"
    enabled: "{{ nomad_enabled }}"
    daemon_reload: true

# Создаем symlink для бинарного файлы nomad
- name: NOMAD | Create symlink for nomad executable
  file:
    src: "{{ nomad_bin_dir }}/nomad"
    dest: /usr/bin/nomad
    state: link
  when: "nomad_bin_dir != '/usr/bin'"

- name: NOMAD | Print Nomad servers addresses with serf port (for masters)
  debug:
    msg: "{{ nomad_servers_serf }}"

- name: NOMAD | Print Nomad servers addresses with rpc port (for clients)
  debug:
    msg: "{{ nomad_servers_rpc }}"
