---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint

verifier:
  name: testinfra

platforms:
  - name: instance1.nomad
    groups:
      - nomad
    networks:
      - name: nomad
    image: protopopys/systemd-centos:7
    override_command: False
    tty: True
    privileged: True
    security_opts:
      - seccomp=unconfigured
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run/lock

  - name: instance2.nomad
    groups:
      - nomad
    networks:
      - name: nomad
    image: protopopys/systemd-centos:7
    override_command: False
    tty: True
    privileged: True
    security_opts:
      - seccomp=unconfigured
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run/lock

  - name: instance3.nomad
    hostname: instance3
    groups:
      - nomad
    networks:
      - name: nomad
    image: protopopys/systemd-centos:7
    override_command: False
    tty: True
    privileged: True
    security_opts:
      - seccomp=unconfigured
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run/lock

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance1.nomad:
        nomad_node_role: both
      instance2.nomad:
        nomad_node_role: both
      instance3.nomad:
        nomad_node_role: both
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
