---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: testinfra
platforms:
  - name: instance1
    groups:
      - nomad_instances
    image: ${MOLECULE_DISTRO:-centos/systemd }
    privileged: true
    command: /sbin/init
    security_opts:
      - seccomp=unconfigured
    capabilities:
      - SYS_ADMIN
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: instance2
    groups:
      - nomad_instances
    image: ${MOLECULE_DISTRO:-centos/systemd }
    privileged: true
    command: /sbin/init
    security_opts:
      - seccomp=unconfigured
    capabilities:
      - SYS_ADMIN
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: instance3
    groups:
      - nomad_instances
    image: ${MOLECULE_DISTRO:-centos/systemd }
    privileged: true
    command: /sbin/init
    security_opts:
      - seccomp=unconfigured
    capabilities:
      - SYS_ADMIN
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance1:
        nomad_node_role: both
        nomad_advertise_address: "{{ advertise_ip | default(ansible_host) }}"
      instance2:
        nomad_node_role: both
        nomad_advertise_address: "{{ advertise_ip | default(ansible_host) }}"
      instance3:
        nomad_node_role: both
        nomad_advertise_address: "{{ advertise_ip | default(ansible_host) }}"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
